---
swagger: "2.0"
info:
  title: Weather API
  description: API for weather data
  version: 1.0.0
basePath: /api
schemes:
  - http
produces:
  - application/json
paths:
  /weather:
    get:
      summary: Get weather data
      description: Returns weather data for a given station and year
      parameters:
        - name: station_id
          in: query
          description: ID of the weather station
          required: false
          type: string
        - name: year
          in: query
          description: Year for which to retrieve data
          required: false
          type: integer
      responses:
        "200":
          description: Weather data returned
          schema:
            type: array
            items:
              type: object
              properties:
                date:
                  type: string
                  format: date
                station_id:
                  type: string
                min_temp:
                  type: number
                max_temp:
                  type: number
                precipitation:
                  type: number
            required:
              - date
              - station_id
              - min_temp
              - max_temp
              - precipitation
